spring.application.name=auth-service
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fintech-ai-system
spring.datasource.username=root
spring.datasource.password=Samarthk@91
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

